In [1]:
import numpy as np
np.random.randn(25)

array([-1.43761132,  0.24194586,  0.20702413, -1.73115531, -0.02595056,
        1.59697225,  2.06491333,  1.35488605, -0.48427583,  0.13166702,
       -1.29000602,  0.07352459,  2.09957677, -0.87160321,  1.04490034,
       -0.41375071, -1.10407822,  0.2778021 , -0.02310765,  0.96669355,
       -1.24140057,  0.89362854, -0.81379121, -0.55571091, -0.73793983])

In [2]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [7]:
x=np.arange(1,101).reshape(10,10)
print(x)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [4]:
x[[1,5,6]]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]])

In [8]:
x[3:]

array([[ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [9]:
x[:,3:8]

array([[ 4,  5,  6,  7,  8],
       [14, 15, 16, 17, 18],
       [24, 25, 26, 27, 28],
       [34, 35, 36, 37, 38],
       [44, 45, 46, 47, 48],
       [54, 55, 56, 57, 58],
       [64, 65, 66, 67, 68],
       [74, 75, 76, 77, 78],
       [84, 85, 86, 87, 88],
       [94, 95, 96, 97, 98]])

In [10]:
x[3:6,1:8]

array([[32, 33, 34, 35, 36, 37, 38],
       [42, 43, 44, 45, 46, 47, 48],
       [52, 53, 54, 55, 56, 57, 58]])

In [3]:
import numpy as np
np.random.rand(1000)

array([0.77766403, 0.71663569, 0.31634083, 0.19265354, 0.37028128,
       0.41873625, 0.72825049, 0.90156028, 0.04992453, 0.11281346,
       0.83043369, 0.91338773, 0.63315516, 0.66676427, 0.04942685,
       0.13069077, 0.86887005, 0.3979901 , 0.98515545, 0.87112871,
       0.90584087, 0.34402742, 0.32498486, 0.81813934, 0.57599829,
       0.3601144 , 0.4282844 , 0.71509655, 0.9330409 , 0.95724161,
       0.31721849, 0.79347555, 0.18785995, 0.52878068, 0.57523901,
       0.830734  , 0.34137279, 0.67551243, 0.17050539, 0.03980098,
       0.6126839 , 0.4496024 , 0.61771024, 0.92506297, 0.93327851,
       0.29555355, 0.87757103, 0.01026838, 0.4003232 , 0.6375776 ,
       0.94088386, 0.75661497, 0.59522479, 0.11027256, 0.59090124,
       0.35014188, 0.28688946, 0.9891981 , 0.60359807, 0.71938238,
       0.79996054, 0.48427296, 0.03117189, 0.88546079, 0.44769394,
       0.34865443, 0.06188532, 0.4896154 , 0.9728148 , 0.24694944,
       0.0946229 , 0.72407205, 0.13795892, 0.50465807, 0.52788

In [4]:
a = np.array([[7, 2], [5, 4]])
np.mean(a)

4.5

In [5]:
np.median(a)

4.5

In [6]:
np.std(a)

1.8027756377319946

In [7]:
a = np.array([[7, 1, 1, 7],
             [9, 4, 3, 8],
             [6, 1, 9, 7],
             [9, 7, 2, 5],
             [5, 1, 5, 9]])
a

array([[7, 1, 1, 7],
       [9, 4, 3, 8],
       [6, 1, 9, 7],
       [9, 7, 2, 5],
       [5, 1, 5, 9]])

In [8]:
from scipy import stats
stats.mode(a)

ModeResult(mode=array([[9, 1, 1, 7]]), count=array([[2, 3, 1, 2]]))